### ISSUE TITLE
Live tv in SD Qualität

### ISSUE THREAD

**Issue by laoneo** [goggle/plugin.video.srfplaytv#2]
Das Live Programm wird nur in SD Qualität übertragen. Ist dies gewollt?

**Comment by goggle** [comment]
Yes. Unfortunately, srf.ch broadcasts their live TV only up to 360p (see e.g. https://www.srf.ch/livestream/player/srf-1).

Only live sport events are usually available in HD.

**Comment by laoneo** [comment]
Ok thanks
