### ISSUE TITLE
Cannot play "Live TV"

### ISSUE THREAD

**Issue by l0rn0r** [goggle/plugin.video.srfplaytv#4]
Hi, since a few days I cannot play "Live TV" in the SRF Play TV Add-On. Doesn't work in Kodi 17.6 running on Linux Solus 3.9999 (also doesn't work on Android).

Attached the debug log (replaced username with "user"):
[18_12_01_ErrorLog_LiveTV.txt](https://github.com/goggle/plugin.video.srfplaytv/files/2635743/18_12_01_ErrorLog_LiveTV.txt)

Thanks for your work, appreciate it!
Screenshot:
![screenshot_srfplaytv_error](https://user-images.githubusercontent.com/21077743/49326354-5e6a9700-f551-11e8-8508-563f2228106c.png)

**Comment by goggle** [comment]
Hi @l0rn0r 

Thanks for reporting this. I'm currently working on moving all the API stuff into a separate module, but I think I could track down the issue and deployed a quick fix. As soon as this PR (https://github.com/xbmc/repo-plugins/pull/2178) gets merged, you should be able to update to the new version 1.2.1, which should resolve this issue. Let me know if it works for you.

**Comment by l0rn0r** [comment]
Hi @goggle 
Thanks for your fast reaction - I just got version 1.2.1 and "Live TV" runs again!
Many thanks for this great add-on, it's very helpful (since the official SRF apps suck :)).
