### ISSUE TITLE
Integrate SRF audio [Feature Request]

### ISSUE THREAD

**Issue by MrReSc** [goggle/plugin.video.srfplaytv#6]
It would be cool if SRF's audio offering were also available through your add-on. Podcasts and live radio streams are available through the [srgssr-audio API](https://developer.srgssr.ch/apis/srgssr-audio/docs).

**Comment by goggle** [comment]
I agree, this would be cool. But I think, this should be done in a new plugin. I'm currently working on a library (script.module.srgssr) to reduce the duplicated code in plugin.video.srfplaytv and plugin.video.rtsplaytv. After I've done this migration, I can think of making a new plugin for the audio platform.

**Comment by goggle** [comment]
This is now done in the new plugin `plugin.audio.srfplayradio`, which you can find [here](https://github.com/goggle/plugin.audio.srfplayradio). As soon as the PR https://github.com/xbmc/repo-plugins/pull/2347 gets accepted, it will be available in the Leia repository.
